name: Ingest Dependabot Data into Port

on:
  workflow_dispatch:

jobs:
  ingest-dependabot-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Dependabot Data
        id: fetch_dependabot
        run: |
          mkdir -p dependabot
          curl -L 'https://api.github.com/repos/${{ github.repository }}/dependabot/alerts' \
          -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          -o dependabot/dependabot-output.json        

      - name: Print JSON Data (Debug Step)
        run: cat dependabot/dependabot-output.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Process Dependabot Data
        run: python3 scripts/process_dependabot.py
        env:
          PORT_API_KEY: ${{ secrets.PORT_JWT_TOKEN }}

      - name: Upload Processed Data to Port
        run: python3 scripts/upload_to_port.py
        env:
          PORT_API_KEY: ${{ secrets.PORT_JWT_TOKEN }}
