name: Ingest Dependabot Data

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Dependabot processing script
        run: |
          python scripts/process_dependabot.py
        env:
          PORT_API_KEY: ${{ secrets.PORT_JWT_TOKEN }}

      - name: Upload data to Port
        run: |
          python scripts/upload_to_port.py
        env:
          PORT_API_KEY: ${{ secrets.PORT_JWT_TOKEN }}
